---
  AllCops:
    NewCops: disable

  Style/Documentation:
    Enabled: false

  Style/FrozenStringLiteralComment:
    Enabled: false

  Naming/MethodName:
    Enabled: false

  Naming/AsciiIdentifiers:
    Enabled: false

  Layout/LineLength:
    Max: 160

  Metrics/MethodLength:
    Max: 20

  Metrics/AbcSize:
    Enabled: false

  Metrics/CyclomaticComplexity:
    Max: 10

  Metrics/ClassLength:
    Enabled: false

  Style/RedundantSort:
    Enabled: false

  Lint/UnreachableLoop:
    Enabled: false
